# version: '3.8'
services:
  app:
    image: backend-app:latest
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
    